### ISSUE TITLE
Suddenly getting failed updating jwt tocken 

### ISSUE THREAD

**Issue by faspina** [Southern-Company-HA/southern-company-hacs#17] opened 2023-03-09 12:36 UTC
## Version of the custom_component

0.1.5
## Debug log

Nothing in the logs related to southern company

```
its been working great until today. I think today is the 1st day of the billing cycle

**Comment by chicagoandy** [comment] 2023-03-09 19:12
I have the same problem, but I after setting debug logs I get:

2023-03-09 07:19:27.209 ERROR (MainThread) [custom_components.southern_company_hacs.coordinator] Error fetching Southern Company Hacs data: Failed updating jwt token

Which admittedly isn't helpful.

**Comment by Lash-L** [comment] 2023-03-09 19:51
Seems they changed their api call last night. I have pushed a fix. Update your instance

**Comment by faspina** [comment] 2023-03-09 23:23
It’s working with the new update

**Comment by spiralfive** [comment] 2023-03-13 12:02
I recently installed this - version 0.1.6 in HACS. It was working fine for a couple of days, but now I am also seeing the token error.

![2DA619D3-C09E-4972-95FE-68F1CB12958D](https://user-images.githubusercontent.com/26095643/224696244-f038dfd9-7da9-4d38-b7da-9f4eb6c3f2d0.jpeg)

**Comment by Lash-L** [comment] 2023-03-13 13:08
@spiralfive This is a current bug I know about - but haven't been above to solve. Every 3 hours the auth token refreshes but it fails updating on that go around. It is then good the next hour.

Check your data and you shouldn't be missing anything.

**Comment by spiralfive** [comment] 2023-03-14 10:06
@Lash-L I May be looking at this wrong - but it appears new data also stopped being downloaded on the 10th. All of the entities look the same/flat also, like the data is not updating anymore. I’m on my phone now, but I can see if there are any log messages later today.
![401D72D4-013A-4BC1-8668-C9BC5BDD3ABE](https://user-images.githubusercontent.com/26095643/224966617-f2c168a5-e55e-4e47-8ed0-b29dbc926a87.jpeg)

**Comment by Lash-L** [comment] 2023-03-14 11:53
> @Lash-L I May be looking at this wrong - but it appears new data also stopped being downloaded on the 10th. All of the entities look the same/flat also, like the data is not updating anymore. I’m on my phone now, but I can see if there are any log messages later today.
> 
> ![401D72D4-013A-4BC1-8668-C9BC5BDD3ABE](https://user-images.githubusercontent.com/26095643/224966617-f2c168a5-e55e-4e47-8ed0-b29dbc926a87.jpeg)
> 
> 

Look at ga powers website at hourly data. If there is more there than you have on home assist then there's a problem. But mine also stops on the 10th right now

And the entities should be a flag line most of the time, they don't change more than a few times a day

**Comment by faspina** [comment] 2023-03-14 17:58
It looks like integration to the API stops working for a period of time,
all the entities then report unknown, then it will authenticate and get the
right values, the value are correct and match what I get from AlabamaPower
in a email about 10:00 . So the problem is occasionally the integration
stops for a period of time  it doesn't seem to indicated a pattern



![alabamapower](https://user-images.githubusercontent.com/17969900/225095920-c7494e8e-0578-40df-b6f7-5d75f1ee74ad.PNG)

**Comment by Lash-L** [comment] 2023-03-14 18:10
> It looks like integration to the API stops working for a period of time,
> 
> all the entities then report unknown, then it will authenticate and get the
> 
> right values, the value are correct and match what I get from AlabamaPower
> 
> in a email about 10:00 . So the problem is occasionally the integration
> 
> stops for a period of time  it doesn't seem to indicated a pattern
> 
> 
> 
> 
> 
> 
> 
> ![alabamapower](https://user-images.githubusercontent.com/17969900/225095920-c7494e8e-0578-40df-b6f7-5d75f1ee74ad.PNG)
> 
> 

Yeah - I'm aware of this issue, I have yet to be able to find the cause. All functionality should still work though 

Do you have any problems using this integration with Alabama power? You're the first I've heard that has been testing it with apc

**Comment by Lash-L** [comment] 2023-03-19 17:25
The random disconnects should be primarily fixed in the latest version

**Closed as completed** 2023-03-28 01:15 UTC
